### PR TITLE
Generate ICD valuesets for all categories

### PR DESCRIPTION
**Pull request by martinbreu**
Release v0.1.0, jar will be attached.

### CODE REVIEW

**Review by alexanderkiel — CHANGES_REQUESTED** [review]
I get the following warnings from Maven:
```
[WARNING] Some problems were encountered while building the effective model for de.samply:fhir-valueset-gen:jar:0.0.1-SNAPSHOT
[WARNING] 'dependencies.dependency.version' for org.junit.jupiter:junit-jupiter:jar is either LATEST or RELEASE (both of them are being deprecated) @ line 26, column 22
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 41, column 17
```

**Comment by alexanderkiel** [comment]
Also:
```
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
```
Can be fixed with:
```
<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
</properties>
```

**Comment by alexanderkiel** [comment]
The ValueSet resources generated have no `.json` file ending.

**Comment by martinbreu** [comment]
Thank you! Warnings fixed and ValueSets renamed to A00.json, A01.json, ...

**Review by alexanderkiel — APPROVED** [review]

**Pull request merged**
